<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun_opts = rerun.to_s.strip.empty? ? "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
std_opts = "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} --strict --tags ~@wip"
%>
default: <%= std_opts %> features
wip: --tags @wip:3 --wip features
xml_report: -t ~@wip --format junit --out ./log/tta_cukes_result
html: -t ~@wip --format html --out ./log/tta_cukes_html_result.html features
rerun: <%= rerun_opts %> --format rerun --out rerun.txt --strict --tags ~@wip
