development:
  adapter: mysql2
  encoding: utf8
  database: tta
  pool: 5
  username: root

test: &test
  adapter: mysql2
  encoding: utf8
  database: tta_test
  pool: 5
  username: root

production:
  adapter: mysql2
  encoding: utf8
  database: tta_prod
  pool: 5
  username: <%= ENV["PROD_USER"] %>
  password: <%= ENV["PROD_PWD"] %>

cucumber:
  <<: *test