#DATA RANGE INDICATES DATA CAN BE UPLOADED 20 DAYS PRIOR TO CURRENT DATE AND TIME
#
######################################## PROJECT 1 #######################################

PROJECT 1:
  - SUB_PROJECT 1.1:
    - MAX_METADATA_ROWS: 30
    - MAX_TESTSUITE_ROWS: 27
    - MAX_NUMBER_OF_TEST_OR_FAILURE_FOR_EVERY_TEST_SUITE: 25
    - MAX_TESTCASE_ROWS: 15
    - MAX_TIME_TAKEN_FOR_INDIVIDUAL_TEST_TO_RUN: 43
    - DATA_RANGE_FOR_METADATA_UPLOAD: 27
  - SUB_PROJECT 1.2:
      - MAX_METADATA_ROWS: 2
      - MAX_TESTSUITE_ROWS: 1
      - MAX_NUMBER_OF_TEST_OR_FAILURE_FOR_EVERY_TEST_SUITE: 10
      - MAX_TESTCASE_ROWS: 2
      - MAX_TIME_TAKEN_FOR_INDIVIDUAL_TEST_TO_RUN: 10
      - DATA_RANGE_FOR_METADATA_UPLOAD: 10
  - SUB_PROJECT 1.3:
      - MAX_METADATA_ROWS: 15
      - MAX_TESTSUITE_ROWS: 9
      - MAX_NUMBER_OF_TEST_OR_FAILURE_FOR_EVERY_TEST_SUITE: 35
      - MAX_TESTCASE_ROWS: 7
      - MAX_TIME_TAKEN_FOR_INDIVIDUAL_TEST_TO_RUN: 13
      - DATA_RANGE_FOR_METADATA_UPLOAD: 15
  - SUB_PROJECT 1.4:
      - MAX_METADATA_ROWS: 7
      - MAX_TESTSUITE_ROWS: 4
      - MAX_NUMBER_OF_TEST_OR_FAILURE_FOR_EVERY_TEST_SUITE: 15
      - MAX_TESTCASE_ROWS: 3
      - MAX_TIME_TAKEN_FOR_INDIVIDUAL_TEST_TO_RUN: 10
      - DATA_RANGE_FOR_METADATA_UPLOAD: 15

######################################### PROJECT 2 #######################################

PROJECT 2:
  - SUB_PROJECT 2.1:
    - MAX_METADATA_ROWS: 6
    - MAX_TESTSUITE_ROWS: 2
    - MAX_NUMBER_OF_TEST_OR_FAILURE_FOR_EVERY_TEST_SUITE: 17
    - MAX_TESTCASE_ROWS: 3
    - MAX_TIME_TAKEN_FOR_INDIVIDUAL_TEST_TO_RUN: 8
    - DATA_RANGE_FOR_METADATA_UPLOAD: 8

######################################### PROJECT 3 #######################################

PROJECT 3:
  - SUB_PROJECT 3.1:
    - MAX_METADATA_ROWS: 40
    - MAX_TESTSUITE_ROWS: 30
    - MAX_NUMBER_OF_TEST_OR_FAILURE_FOR_EVERY_TEST_SUITE: 30
    - MAX_TESTCASE_ROWS: 15
    - MAX_TIME_TAKEN_FOR_INDIVIDUAL_TEST_TO_RUN: 50
    - DATA_RANGE_FOR_METADATA_UPLOAD: 18
  - SUB_PROJECT 3.2:
      - MAX_METADATA_ROWS: 20
      - MAX_TESTSUITE_ROWS: 8
      - MAX_NUMBER_OF_TEST_OR_FAILURE_FOR_EVERY_TEST_SUITE: 25
      - MAX_TESTCASE_ROWS: 5
      - MAX_TIME_TAKEN_FOR_INDIVIDUAL_TEST_TO_RUN: 30
      - DATA_RANGE_FOR_METADATA_UPLOAD: 22
  - SUB_PROJECT 3.3:
      - MAX_METADATA_ROWS: 5
      - MAX_TESTSUITE_ROWS: 18
      - MAX_NUMBER_OF_TEST_OR_FAILURE_FOR_EVERY_TEST_SUITE: 30
      - MAX_TESTCASE_ROWS: 8
      - MAX_TIME_TAKEN_FOR_INDIVIDUAL_TEST_TO_RUN: 39
      - DATA_RANGE_FOR_METADATA_UPLOAD: 22

############################################################################################